module.exports = {
  names: [
    'Horatio', 'Agnes', 'Mildred', 'Nigel', 'Barnaby',
    'Winifred', 'Prudence', 'Cedric', 'Hortense', 'Oswald',
    'Beatrice', 'Thaddeus', 'Constance', 'Algernon', 'Muriel',
    'Rupert', 'Sybil', 'Gertrude', 'Percival', 'Dorothea',
    'Reginald', 'Lesley', 'Rowan', 'Jules', 'Morgan',
    'Jon H', 'Sam K', 'Pat L', 'Alex M', 'Robin D',
    'Chris R', 'Kim W', 'Ellis B', 'Frankie C', 'Jamie F',
    'Casey Q', 'Drew U', 'Quinn A', 'Clive U', 'Ethel A',
    'Penelope Z', 'Ivor N', 'Mabel J', 'Basil F', 'Enid P',
    'Cyril W', 'Nora G', 'Hector S', 'Ida V', 'Walter Q'
  ],
  reasons: {
    sun: [
      'For a barbecue that has already been postponed twice',
      'It is the annual snail race',
      'A wedding. The marquee is non-refundable',
      'To dry the washing before Mother arrives',
      'The village fete cannot operate under a cloud',
      'A picnic that takes umbrage at umbrellas',
      'The cricket is in the parish magazine; it cannot rain',
      'To photograph a dog in a hat, in proper light',
      'Painting a fence that must not be rained on',
      'A proposal on a hill, with sandwiches',
      'The tomatoes have demanded it in writing',
      'So the deckchair can be used without irony'
    ],
    rain: [
      'To cancel a walk with relations',
      'The garden has become overconfident',
      'A respectable excuse to stew indoors',
      'The ducks have submitted a petition',
      'To give a new umbrella a stern outing',
      'A romantic puddle, according to someone',
      'The roof has been asking for it',
      'So the prize marrow can drink without comment',
      'A funeral for a houseplant, preferably damp',
      'To make the bookshop smell correct',
      'The snails requested a rest from racing',
      'Because the gutters need the practice'
    ],
    snow: [
      'To justify a ridiculous hat',
      'A snowman has been promised to a small tyrant',
      'Sledges have been got out and cannot go back',
      'To post a letter looking picturesque',
      'The school play needs a white backdrop, allegedly',
      'So the cat can be offended by the garden',
      'A proper reason to scrape the path badly',
      'The kettle deserves an audience',
      'To lose a glove with dignity',
      'Village gossip requires footprints',
      'Because January should look like itself',
      'A snowball has been scheduled'
    ],
    drizzle: [
      'A walk that must be damp but not dramatic',
      'To test whether the washing minds',
      'Soft weather for a mild sulk',
      'The roses prefer a polite mist',
      'So umbrellas can stay at home and still be right',
      'A cemetery visit at half-commitment',
      'The dog requires a smellier walk',
      'Because full rain would be showing off',
      'To fog up a bus window on purpose',
      'A picnic that expected this, really',
      'Light moisture for the snails\' warm-up',
      'The kind of weather that justifies soup'
    ],
    fog: [
      'To miss an appointment with plausible deniability',
      'Hiding from relations at the station',
      'The pier should be rumoured, not seen',
      'A photograph of nothing, on purpose',
      'So the lighthouse can feel needed',
      'To walk the dog without meeting the dog\'s friends',
      'Atmospheric cover for a bad haircut',
      'The hill is better as a suggestion',
      'Because the harbour likes secrets',
      'A ghost tour that paid for fog',
      'To smuggle a cake past neighbours',
      'Lost, but make it scenic'
    ],
    storm: [
      'To cancel everything with authority',
      'The washing line has been too smug',
      'A reason to shout indoors',
      'The trees requested a vigorous meeting',
      'So the candles can come out without looking keen',
      'Dramatic weather for an undramatic argument',
      'To test the roof\'s sense of humour',
      'A night for soup and unearned gravity',
      'The bin lids have a score to settle',
      'Because the sea ought to make a speech',
      'A proper excuse to stay put',
      'Lightning, for the correspondence'
    ]
  }
};
